### ISSUE TITLE
["BUG"] Update the changelog

### ISSUE THREAD

**Issue by MaferMazu** [eduNEXT/eox-tenant#147]
**Describe the bug**
The changelog is outdated.

**Expected behavior**
Have this info in the changelog https://github.com/eduNEXT/eox-tenant/releases/tag/v6.0.0

**Comment by JuanDavidBuitrago** [comment]
@MaferMazu, The changelog is update: https://github.com/eduNEXT/eox-tenant/commit/4c16a6832f6155339c57e151b5cea12f0a1da6be
