### ISSUE TITLE
["BUG"] Tenant organization is created but not associated when sites are created

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/eox-tenant#171]
**Describe the bug**
When one saves a tenant config object, an tenant organization should be created, and associated with the current site. The second part is not happening

**To Reproduce**
1. Go to '/admin/eox_tenant/tenantconfig/' and select a tenant config.
2. Click on 'save'
3. Verify tenant organization is not associated: /admin/eox_tenant/tenantorganization/

**Expected behavior**
Tenant organization is associated with the tenant config.

**Comment by Ian2012** [comment]
@eduNEXT/dedalo

**Comment by mariajgrimaldi** [comment]
can we blur the client's information? thanks!

**Comment by Ian2012** [comment]
@mariajgrimaldi done, the information will be added in an internal ticket

**Comment by Ian2012** [comment]
I will close this issue as this is duplicated from https://github.com/eduNEXT/eox-tenant/issues/154
