### ISSUE TITLE
["BUG"] FilterUserCourseEnrollmentsByTenant doesn't modify all needed views

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/eox-tenant#175]
**Describe the bug**
Views like `api/enrollment/v1/enrollments/` are not filtered correctly.

**To Reproduce**
0. Crea at least two organizations, each one associated to only one tenant, and enroll users to course belonging to those organizations.
1. Go to 'api/enrollment/v1/enrollments/' 
2. See all enrollment without filters

**Expected behavior**
FIlter enrollments using the current site.

**Additional context**
This is the view I found, but there might be others

**Comment by JuanDavidBuitrago** [comment]
Closed this because I created it in edunext-platform: https://github.com/eduNEXT/edunext-platform/issues/737
