### ISSUE TITLE
["BUG"] Tenant organization admin search

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/eox-tenant#176]
**Describe the bug**
We sometimes need to access the tenant organization admin and search for some client organizations for troubleshooting and fixes. As we have many Tenants associated to one organization, the time to load the page is higher and increases the memory usage, which arrives in 502 error as the container is stopped.

One can increase the memory but the higher load times can lead to timeout errors.

**Expected behavior**
It should load faster without errors.

**Comment by JuanDavidBuitrago** [comment]
Hi @Ian2012, thanks for reporting this.

Can you please provide us with more context to be able to replicate the bug, in which version does this occur? Does the problem occur in SAAS? How often is this happening?

**Comment by JuanDavidBuitrago** [comment]
Sorry for the delay, we are trying to include this in one of ours sprints to work on it.

**Comment by Ian2012** [comment]
cc @DeimerM @DonatoBD

**Comment by Alec4r** [comment]
Hi @Ian2012 we are planning add this bug to our next sprint but first we will need a environment with data enough to make the tests, @eduNEXT/atlas-team could you help us with and environment?

**Comment by MoisesGSalas** [comment]
@Alec4r: In that case you can use the SaaS US staging environment, you can ask @DeimerM or @DonatoBD for further details.

**Comment by MaferMazu** [comment]
@Ian2012, is this still happening?

**Comment by Ian2012** [comment]
cc @DeimerM

**Comment by MaferMazu** [comment]
I'll close this because of the inactivity and the uncertainty of whether this is still needed. Please feel free to reopen if you need us to look at this.
