### ISSUE TITLE
["FEAT"] Palm compatibility

### ISSUE THREAD

**Issue by andrey-canon** [eduNEXT/eox-tenant#180]
**Is your feature request related to a problem? Please describe.**
Since  Palm release was cut on April 11th 2023, I would like to know if there is an eox-tenant date release for Palm version. Thanks

**Describe the solution you'd like**
Palm compatibility

**Comment by JuanDavidBuitrago** [comment]
@santiagosuarezedunext, could you answer this?

**Comment by JuanDavidBuitrago** [comment]
I don't know if it will be part of ours next plans, maybe do you know? @MaferMazu

**Comment by santiagosuarezedunext** [comment]
@andrey-canon @JuanDavidBuitrago We are going to discuss which version to update all the exs after half of the year but i would think that it is for Palm

**Comment by MaferMazu** [comment]
@andrey-canon, we plan to start the palm migration of the eoxs after 10th June, a day after the release was announced, following this https://openedx.atlassian.net/wiki/spaces/COMM/pages/3613392957/Open+edX+Release+Schedule

Do you need eox-tenant before that date?

**Comment by andrey-canon** [comment]
No, I was just asking in order to plan our migration, thanks all for your answer :)

**Comment by Asespinel** [comment]
@santiagosuarezedunext Do we have new updates about this issue?

**Comment by santiagosuarezedunext** [comment]
@Asespinel I think the Dédalo team will be able to start the migration to Palm after finishing some prioritized projects.
